"""Initial migration

Revision ID: 02c3ccdbe6fa
Revises: 
Create Date: 2025-11-16 14:33:04.453491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '02c3ccdbe6fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ADMIN',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('account_username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_system_account', sa.Boolean(), nullable=False),
    sa.Column('is_system_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('account_username')
    )

    op.create_table('DOCTOR',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('doctor_login_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('doctor_login_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('PATIENT',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_code', sa.String(), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_password_token', sa.String(), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('suspended_until', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('card_number')
    )
    op.create_table('MEDICAL_RECORD',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['DOCTOR.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['PATIENT.patient_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('SCHEDULE',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('recurring_group_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='available', nullable=False),
    sa.Column('max_patients', sa.Integer(), nullable=False),
    sa.Column('booked_patients', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['DOCTOR.doctor_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_SCHEDULE_recurring_group_id'), 'SCHEDULE', ['recurring_group_id'], unique=False)
    op.create_table('ROOM_DAY',
    sa.Column('room_day_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('next_sequence', sa.Integer(), nullable=False),
    sa.Column('current_called_sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['SCHEDULE.schedule_id'], ),
    sa.PrimaryKeyConstraint('room_day_id'),
    sa.UniqueConstraint('schedule_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['DOCTOR.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['PATIENT.patient_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['SCHEDULE.schedule_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('CHECKIN',
    sa.Column('checkin_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('checkin_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkin_method', sa.Enum('onsite', 'online', name="checkin_method"), nullable=True),
    sa.Column('ticket_sequence', sa.Integer(), nullable=True),
    sa.Column('ticket_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('checked_in', 'no_show', 'seen', name="checkin_status"), nullable=False),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.ForeignKeyConstraint(['cancelled_by'], ['ADMIN.admin_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['PATIENT.patient_id'], ),
    sa.PrimaryKeyConstraint('checkin_id')
    )
    op.create_table('INFRACTION',
    sa.Column('infraction_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('infraction_type', sa.Enum('no_show', 'late_cancel', 'other', name="infraction_type"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('penalty_applied', sa.Boolean(), nullable=False),
    sa.Column('penalty_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['PATIENT.patient_id'], ),
    sa.PrimaryKeyConstraint('infraction_id')
    )
    op.create_table('VISIT_CALL',
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('ticket_sequence', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('called_by', sa.UUID(), nullable=True),
    sa.Column('call_type', sa.Enum('call', 'recall', 'skip', name="call_type"), nullable=False),
    sa.Column('call_status', sa.Enum('active', 'expired', 'attended', name="call_status"), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], ),
    sa.ForeignKeyConstraint(['called_by'], ['ADMIN.admin_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_table('LEAVE_REQUEST',
    sa.Column('leave_request_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['DOCTOR.doctor_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['SCHEDULE.schedule_id'], ),
    sa.PrimaryKeyConstraint('leave_request_id'),
    sa.UniqueConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LEAVE_REQUEST')
    op.drop_table('VISIT_CALL')
    op.drop_table('INFRACTION')
    op.drop_table('CHECKIN')
    op.drop_table('appointment')
    op.drop_table('ROOM_DAY')
    op.drop_index(op.f('ix_SCHEDULE_recurring_group_id'), table_name='SCHEDULE')
    op.drop_table('SCHEDULE')
    op.drop_table('MEDICAL_RECORD')
    op.drop_table('PATIENT')
    op.drop_table('DOCTOR')

    op.drop_table('ADMIN')
    # ### end Alembic commands ###