"""create leave_requests table and update schedule relationship

Revision ID: 05efa2d151f7
Revises: 9b9ed8aeb6e1
Create Date: 2025-11-13 07:28:05.380235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05efa2d151f7'
down_revision: Union[str, Sequence[str], None] = '9b9ed8aeb6e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LEAVE_REQUEST',
    sa.Column('leave_request_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['DOCTOR.doctor_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['SCHEDULE.schedule_id'], ),
    sa.PrimaryKeyConstraint('leave_request_id'),
    sa.UniqueConstraint('schedule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LEAVE_REQUEST')
    # ### end Alembic commands ###
