"""add email verification fields to patient

Revision ID: 1d4349be0ba5
Revises: 05efa2d151f7
Create Date: 2025-11-13 08:17:25.189175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4349be0ba5'
down_revision: Union[str, Sequence[str], None] = '05efa2d151f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PATIENT', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('FALSE')))
    op.add_column('PATIENT', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('PATIENT', sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PATIENT', 'code_expires_at')
    op.drop_column('PATIENT', 'verification_code')
    op.drop_column('PATIENT', 'is_verified')
    # ### end Alembic commands ###
