"""Add status to Checkin model

Revision ID: 51f63bc71737
Revises: f9b7c7a2385a
Create Date: 2025-11-15 15:08:04.521670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51f63bc71737'
down_revision: Union[str, Sequence[str], None] = 'f9b7c7a2385a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    checkin_status_enum = sa.Enum('checked_in', 'no_show', 'seen', name='checkin_status')
    checkin_status_enum.create(op.get_bind())

    op.add_column('CHECKIN', sa.Column('status', checkin_status_enum, nullable=False, server_default='checked_in'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CHECKIN', 'status')
    # Drop the ENUM type
    checkin_status_enum = sa.Enum('checked_in', 'no_show', 'seen', name='checkin_status')
    checkin_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
