"""Create Appointment model and relationships

Revision ID: 5b43e55e0f08
Revises: f290f03c3b4a
Create Date: 2025-11-12 14:24:22.378310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b43e55e0f08'
down_revision: Union[str, Sequence[str], None] = 'f290f03c3b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the ENUM type object, but prevent SQLAlchemy from automatically creating the type
appointment_status_enum = postgresql.ENUM(
    'scheduled', 'confirmed', 'waitlist', 'cancelled', 'checked_in', 
    'waiting', 'called', 'in_consult', 'completed', 'no_show', 
    name='appointment_status',
    create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually and safely create the ENUM type if it doesn't exist
    op.execute("""
        DO $_PSQL_$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'appointment_status') THEN
                CREATE TYPE appointment_status AS ENUM ('scheduled', 'confirmed', 'waitlist', 'cancelled', 'checked_in', 'waiting', 'called', 'in_consult', 'completed', 'no_show');
            END IF;
        END
        $_PSQL_$;
    """)

    # 1. Drop foreign key constraints that reference the old APPOINTMENT table
    op.drop_constraint('CHECKIN_appointment_id_fkey', 'CHECKIN', type_='foreignkey')
    op.drop_constraint('INFRACTION_appointment_id_fkey', 'INFRACTION', type_='foreignkey')
    op.drop_constraint('VISIT_CALL_appointment_id_fkey', 'VISIT_CALL', type_='foreignkey')

    # 2. Drop the old APPOINTMENT table
    op.drop_table('APPOINTMENT')

    # 3. Create the new 'appointment' table with correct ENUM for status
    op.create_table('appointment',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.Column('status', appointment_status_enum, nullable=False), # Use the created ENUM
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['DOCTOR.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['PATIENT.patient_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )

    # 4. Create foreign key constraints that reference the new 'appointment' table
    op.create_foreign_key('CHECKIN_appointment_id_fkey', 'CHECKIN', 'appointment', ['appointment_id'], ['appointment_id'])
    op.create_foreign_key('INFRACTION_appointment_id_fkey', 'INFRACTION', 'appointment', ['appointment_id'], ['appointment_id'])
    op.create_foreign_key('VISIT_CALL_appointment_id_fkey', 'VISIT_CALL', 'appointment', ['appointment_id'], ['appointment_id'])

    # Handle the index on SCHEDULE (if it's a desired change)
    op.create_index(op.f('ix_SCHEDULE_recurring_group_id'), 'SCHEDULE', ['recurring_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Drop foreign key constraints that reference the new 'appointment' table
    op.drop_constraint('CHECKIN_appointment_id_fkey', 'CHECKIN', type_='foreignkey')
    op.drop_constraint('INFRACTION_appointment_id_fkey', 'INFRACTION', type_='foreignkey')
    op.drop_constraint('VISIT_CALL_appointment_id_fkey', 'VISIT_CALL', type_='foreignkey')

    # 2. Drop the new 'appointment' table
    op.drop_table('appointment')

    # 3. Recreate the old 'APPOINTMENT' table
    op.create_table('APPOINTMENT',
    sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('time_period', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', appointment_status_enum, autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['DOCTOR.doctor_id'], name='APPOINTMENT_doctor_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['PATIENT.patient_id'], name='APPOINTMENT_patient_id_fkey'),
    sa.PrimaryKeyConstraint('appointment_id', name='APPOINTMENT_pkey')
    )

    # 4. Recreate foreign key constraints that reference the old 'APPOINTMENT' table
    op.create_foreign_key('CHECKIN_appointment_id_fkey', 'CHECKIN', 'APPOINTMENT', ['appointment_id'], ['appointment_id'])
    op.create_foreign_key('INFRACTION_appointment_id_fkey', 'INFRACTION', 'APPOINTMENT', ['appointment_id'], ['appointment_id'])
    op.create_foreign_key('VISIT_CALL_appointment_id_fkey', 'VISIT_CALL', 'APPOINTMENT', ['appointment_id'], ['appointment_id'])

    # Handle the index on SCHEDULE
    op.drop_index(op.f('ix_SCHEDULE_recurring_group_id'), table_name='SCHEDULE')

    # Manually drop the ENUM type. It's safe to do this on downgrade.
    op.execute("DROP TYPE IF EXISTS appointment_status;")
    # ### end Alembic commands ###