"""Add department to MedicalRecord

Revision ID: 6069cea56423
Revises: 02c3ccdbe6fa
Create Date: 2025-11-16 16:21:13.419170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.base import UUIDType # Import UUIDType


# revision identifiers, used by Alembic.
revision: str = '6069cea56423'
down_revision: Union[str, Sequence[str], None] = '02c3ccdbe6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MEDICAL_RECORD', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MEDICAL_RECORD', 'department')
    # ### end Alembic commands ###
