"""
Add MedicalRecord model

Revision ID: 7589c943a551
Revises: 51f63bc71737
Create Date: 2025-11-16 06:15:39.764585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.base

# revision identifiers, used by Alembic.
revision: str = '7589c943a551'
down_revision: Union[str, Sequence[str], None] = '51f63bc71737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LEAVE_REQUEST')
    op.alter_column('CHECKIN', 'checkin_id',
               existing_type=sa.UUID(),
               type_=app.db.base.UUIDType(length=36),
               existing_nullable=False)
    # Temporarily drop foreign key constraint before altering column type
    op.drop_constraint('CHECKIN_appointment_id_fkey', 'CHECKIN', type_='foreignkey')

    # Use raw SQL to alter column type and cast existing data
    op.execute("ALTER TABLE \"CHECKIN\" ALTER COLUMN appointment_id TYPE uuid USING appointment_id::uuid")

    # Recreate foreign key constraint after altering column type
    op.create_foreign_key('CHECKIN_appointment_id_fkey', 'CHECKIN', 'appointment', ['appointment_id'], ['appointment_id'])
    # Use raw SQL to alter column type and cast existing data for patient_id
    op.execute("ALTER TABLE \"CHECKIN\" ALTER COLUMN patient_id TYPE uuid USING patient_id::uuid")
    # Use raw SQL to alter column type and cast existing data for cancelled_by
    op.execute("ALTER TABLE \"CHECKIN\" ALTER COLUMN cancelled_by TYPE uuid USING cancelled_by::uuid")
    # Use raw SQL to alter column type and cast existing data for doctor_id
    op.execute("ALTER TABLE \"DOCTOR\" ALTER COLUMN doctor_id TYPE uuid USING doctor_id::uuid")
    op.alter_column('INFRACTION', 'infraction_id',
               existing_type=sa.UUID(),
               type_=app.db.base.UUIDType(length=36),
               existing_nullable=False)
    # Use raw SQL to alter column type and cast existing data for INFRACTION.patient_id
    op.execute("ALTER TABLE \"INFRACTION\" ALTER COLUMN patient_id TYPE uuid USING patient_id::uuid")
    # Use raw SQL to alter column type and cast existing data for INFRACTION.appointment_id
    op.execute("ALTER TABLE \"INFRACTION\" ALTER COLUMN appointment_id TYPE uuid USING appointment_id::uuid")
    op.add_column('MEDICAL_RECORD', sa.Column('appointment_id', sa.String(), nullable=True)) # Add as string first
    op.execute("ALTER TABLE \"MEDICAL_RECORD\" ALTER COLUMN appointment_id TYPE uuid USING appointment_id::uuid")
    op.alter_column('MEDICAL_RECORD', 'record_id',
               existing_type=sa.UUID(),
               type_=app.db.base.UUIDType(length=36),
               existing_nullable=False)
    # Use raw SQL to alter column type and cast existing data for MEDICAL_RECORD.patient_id
    op.execute("ALTER TABLE \"MEDICAL_RECORD\" ALTER COLUMN patient_id TYPE uuid USING patient_id::uuid")
    # Use raw SQL to alter column type and cast existing data for MEDICAL_RECORD.doctor_id
    op.execute("ALTER TABLE \"MEDICAL_RECORD\" ALTER COLUMN doctor_id TYPE uuid USING doctor_id::uuid")
    op.create_foreign_key(None, 'MEDICAL_RECORD', 'appointment', ['appointment_id'], ['appointment_id'])
    # Use raw SQL to alter column type and cast existing data for PATIENT.patient_id
    op.execute("ALTER TABLE \"PATIENT\" ALTER COLUMN patient_id TYPE uuid USING patient_id::uuid")
    op.alter_column('ROOM_DAY', 'room_day_id',
               existing_type=sa.UUID(),
               type_=app.db.base.UUIDType(length=36),
               existing_nullable=False)
    # Use raw SQL to alter column type and cast existing data for ROOM_DAY.schedule_id
    op.execute("ALTER TABLE \"ROOM_DAY\" ALTER COLUMN schedule_id TYPE uuid USING schedule_id::uuid")
    # Use raw SQL to alter column type and cast existing data for SCHEDULE.schedule_id
    op.execute("ALTER TABLE \"SCHEDULE\" ALTER COLUMN schedule_id TYPE uuid USING schedule_id::uuid")
    # Use raw SQL to alter column type and cast existing data for SCHEDULE.doctor_id
    op.execute("ALTER TABLE \"SCHEDULE\" ALTER COLUMN doctor_id TYPE uuid USING doctor_id::uuid")
    op.alter_column('SCHEDULE', 'recurring_group_id',
               existing_type=sa.UUID(),
               type_=app.db.base.UUIDType(length=36),
               existing_nullable=True)
    op.alter_column('VISIT_CALL', 'call_id',
               existing_type=sa.UUID(),
               type_=app.db.base.UUIDType(length=36),
               existing_nullable=False)
    # Use raw SQL to alter column type and cast existing data for VISIT_CALL.appointment_id
    op.execute("ALTER TABLE \"VISIT_CALL\" ALTER COLUMN appointment_id TYPE uuid USING appointment_id::uuid")
    # Use raw SQL to alter column type and cast existing data for VISIT_CALL.called_by
    op.execute("ALTER TABLE \"VISIT_CALL\" ALTER COLUMN called_by TYPE uuid USING called_by::uuid")
    # Use raw SQL to alter column type and cast existing data for appointment.appointment_id
    op.execute("ALTER TABLE \"appointment\" ALTER COLUMN appointment_id TYPE uuid USING appointment_id::uuid")
    # Use raw SQL to alter column type and cast existing data for appointment.patient_id
    op.execute("ALTER TABLE \"appointment\" ALTER COLUMN patient_id TYPE uuid USING patient_id::uuid")
    # Use raw SQL to alter column type and cast existing data for appointment.doctor_id
    op.execute("ALTER TABLE \"appointment\" ALTER COLUMN doctor_id TYPE uuid USING doctor_id::uuid")
    # Use raw SQL to alter column type and cast existing data for appointment.schedule_id
    op.execute("ALTER TABLE \"appointment\" ALTER COLUMN schedule_id TYPE uuid USING schedule_id::uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'schedule_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('appointment', 'doctor_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('appointment', 'patient_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('appointment', 'appointment_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('VISIT_CALL', 'called_by',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('VISIT_CALL', 'appointment_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('VISIT_CALL', 'call_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('SCHEDULE', 'recurring_group_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('SCHEDULE', 'doctor_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('SCHEDULE', 'schedule_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('ROOM_DAY', 'schedule_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('ROOM_DAY', 'room_day_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('PATIENT', 'patient_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'MEDICAL_RECORD', type_='foreignkey')
    op.alter_column('MEDICAL_RECORD', 'doctor_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('MEDICAL_RECORD', 'patient_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('MEDICAL_RECORD', 'record_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('MEDICAL_RECORD', 'appointment_id')
    op.alter_column('INFRACTION', 'appointment_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('INFRACTION', 'patient_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('INFRACTION', 'infraction_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('DOCTOR', 'doctor_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('CHECKIN', 'cancelled_by',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('CHECKIN', 'patient_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('CHECKIN', 'appointment_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('CHECKIN', 'checkin_id',
               existing_type=app.db.base.UUIDType(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_table('LEAVE_REQUEST',
    sa.Column('leave_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('schedule_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['DOCTOR.doctor_id'], name='LEAVE_REQUEST_doctor_id_fkey'),
    sa.ForeignKeyConstraint(['schedule_id'], ['SCHEDULE.schedule_id'], name='LEAVE_REQUEST_schedule_id_fkey'),
    sa.PrimaryKeyConstraint('leave_request_id', name='LEAVE_REQUEST_pkey'),
    sa.UniqueConstraint('schedule_id', name='LEAVE_REQUEST_schedule_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###