"""Add department to Admin model

Revision ID: 8d764d0273ba
Revises: 6069cea56423
Create Date: 2025-11-17 19:43:43.649358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d764d0273ba'
down_revision: Union[str, Sequence[str], None] = '6069cea56423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ADMIN', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ADMIN', 'department')
    # ### end Alembic commands ###
