"""add status to schedule table

Revision ID: 9b9ed8aeb6e1
Revises: f04cf82a4ab3
Create Date: 2025-11-13 06:28:46.201341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9ed8aeb6e1'
down_revision: Union[str, Sequence[str], None] = 'f04cf82a4ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SCHEDULE', sa.Column('status', sa.String(), server_default='available', nullable=False))
    op.alter_column('appointment', 'status',
               existing_type=postgresql.ENUM('scheduled', 'confirmed', 'waitlist', 'cancelled', 'checked_in', 'waiting', 'called', 'in_consult', 'completed', 'no_show', name='appointment_status'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('scheduled', 'confirmed', 'waitlist', 'cancelled', 'checked_in', 'waiting', 'called', 'in_consult', 'completed', 'no_show', name='appointment_status'),
               existing_nullable=False)
    op.drop_column('SCHEDULE', 'status')
    # ### end Alembic commands ###
