"""Add email to Doctor model

Revision ID: a0c51a5c7bbf
Revises: 0d8c63283d96
Create Date: 2025-11-11 13:10:54.076907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c51a5c7bbf'
down_revision: Union[str, Sequence[str], None] = '0d8c63283d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DOCTOR', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'DOCTOR', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DOCTOR', type_='unique')
    op.drop_column('DOCTOR', 'email')
    # ### end Alembic commands ###
