"""add reset password fields to patient

Revision ID: a4360ca17d12
Revises: 1d4349be0ba5
Create Date: 2025-11-14 07:23:47.132266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4360ca17d12'
down_revision: Union[str, Sequence[str], None] = '1d4349be0ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PATIENT', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('PATIENT', sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PATIENT', 'reset_token_expires_at')
    op.drop_column('PATIENT', 'reset_password_token')
    # ### end Alembic commands ###
