"""Add time_period to schedule, remove start/end

Revision ID: a5a33567d8e9
Revises: a0c51a5c7bbf
Create Date: 2025-11-11 17:29:15.664178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text # Import text

# revision identifiers, used by Alembic.
revision: str = 'a5a33567d8e9'
down_revision: Union[str, Sequence[str], None] = 'a0c51a5c7bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add time_period as nullable first
    op.add_column('SCHEDULE', sa.Column('time_period', sa.String(), nullable=True))

    # 2. Update existing rows with a default value
    op.execute(text("UPDATE \"SCHEDULE\" SET time_period = '上午診' WHERE time_period IS NULL"))

    # 3. Alter time_period to be non-nullable
    op.alter_column('SCHEDULE', 'time_period',
               existing_type=sa.String(),
               nullable=False,
               existing_nullable=True)

    # 4. Drop start and end columns
    op.drop_column('SCHEDULE', 'end')
    op.drop_column('SCHEDULE', 'start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SCHEDULE', sa.Column('start', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('SCHEDULE', sa.Column('end', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('SCHEDULE', 'time_period')
    # ### end Alembic commands ###
