"""Add max_patients to Schedule

Revision ID: aa09657862f8
Revises: 5b43e55e0f08
Create Date: 2025-11-12 17:58:49.493306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa09657862f8'
down_revision: Union[str, Sequence[str], None] = '5b43e55e0f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SCHEDULE', sa.Column('max_patients', sa.Integer(), nullable=True))
    op.execute('UPDATE "SCHEDULE" SET max_patients = 10 WHERE max_patients IS NULL')
    op.alter_column('SCHEDULE', 'max_patients', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('scheduled', 'confirmed', 'waitlist', 'cancelled', 'checked_in', 'waiting', 'called', 'in_consult', 'completed', 'no_show', name='appointment_status'),
               existing_nullable=False)
    op.drop_column('SCHEDULE', 'max_patients')
    # ### end Alembic commands ###
