"""Add AuditLog table

Revision ID: aee3f2788a99
Revises: 6069cea56423
Create Date: 2025-11-17 11:50:28.836870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee3f2788a99'
down_revision: Union[str, Sequence[str], None] = '6069cea56423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AUDIT_LOG',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('log_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AUDIT_LOG')
    # ### end Alembic commands ###
