"""Drop audit_log table

Revision ID: edfa75f5350b
Revises: aee3f2788a99
Create Date: 2025-11-17 18:45:44.206520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfa75f5350b'
down_revision: Union[str, Sequence[str], None] = 'aee3f2788a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AUDIT_LOG')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AUDIT_LOG',
    sa.Column('log_id', sa.NUMERIC(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('target_id', sa.VARCHAR(), nullable=True),
    sa.Column('log_metadata', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###
