"""add recurring_group_id to schedule table

Revision ID: f290f03c3b4a
Revises: ca753a48f083
Create Date: 2025-11-12 16:30:05.734293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f290f03c3b4a'
down_revision: Union[str, None] = 'ca753a48f083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SCHEDULE', sa.Column('recurring_group_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SCHEDULE', 'recurring_group_id')
    # ### end Alembic commands ###